In [ ]:
s=str(input('Enter the string:'))
s=s.lower()
reverse=s[::-1]
if s==reverse:
  print(True)
else:
  print(False)

Enter the string:Naan
True

In [ ]:
Input=str(input("Input:"))
Pattern=str(input("Pattern:"))
output=Input.count(Pattern)
output

Input:ABCDCDC
Pattern:CD

2

In [ ]:
A=[]
for i in range(1,11):
  print("Game",i,":")
  player1=str(input("Player1:"))
  player2=str(input("Player2:"))
  if (player1=="R" and player2=="S"):
    print("player1 wins")
    A.append(1)

  elif (player1=="P" and player2=="R"):
   print("player1 wins")
   A.append(1)
  elif (player1=="S" and player2=="P"):
    print("player1 wins")
    A.append(1)
  elif (player1==player2):
    print("Draw")
    A.append(0)
  else:
    print("player2 wins")
    A.append(2)
Player1score=A.count(1)
Player2score=A.count(2)
if Player1score > Player2score:
  print("Final Winner:Player1")
else:
    print("Final Winner:Player2")

Game 1 :
Player1:R
Player2:R
Draw
Game 2 :
Player1:P
Player2:P
Draw
Game 3 :
Player1:S
Player2:S
Draw
Game 4 :
Player1:P
Player2:S
player2 wins
Game 5 :
Player1:P
Player2:R
player1 wins
Game 6 :
Player1:R
Player2:P
player2 wins
Game 7 :
Player1:R
Player2:S
player1 wins
Game 8 :
Player1:S
Player2:P
player1 wins
Game 9 :
Player1:S
Player2:R
player2 wins
Game 10 :
Player1:P
Player2:R
player1 wins
Final Winner:Player1

In [ ]:
import requests
import time

def fetch_bitcoin_price():
    url = "https://api.coindesk.com/v1/bpi/currentprice.json"
    response = requests.get(url)
    data = response.json()
    return data['bpi']['USD']['rate_float']


def collect_data():
    data_points = []
    previous_data_point = None
    count = 0
    while count < 288:
        usd_price = fetch_bitcoin_price()
        if usd_price != previous_data_point:
            data_points.append(usd_price)
            print("Data point", len(data_points), ":", usd_price)
            previous_data_point = usd_price
            count += 1
        time.sleep(5)
    data_points.sort()
    print("highest price is",data_points[-1])
    print("lowest price is",data_points[0])


collect_data()

Data point 1 : 43138.3928
Data point 2 : 43146.4946
Data point 3 : 43140.5383
Data point 4 : 43138.7188
Data point 5 : 43160.7161
Data point 6 : 43157.2321
Data point 7 : 43158.9773
Data point 8 : 43154.3471
Data point 9 : 43166.0253
Data point 10 : 43162.9273
Data point 11 : 43172.2088
Data point 12 : 43180.8175
Data point 13 : 43190.0981
Data point 14 : 43202.9526
Data point 15 : 43207.6481
Data point 16 : 43198.706
Data point 17 : 43185.7776
Data point 18 : 43166.9662
Data point 19 : 43152.4666
Data point 20 : 43154.3461
Data point 21 : 43135.1101
Data point 22 : 43128.1818
Data point 23 : 43137.3702
Data point 24 : 43134.6449
Data point 25 : 43183.6257
Data point 26 : 43200.0139
Data point 27 : 43196.1845
Data point 28 : 43202.6469
Data point 29 : 43210.1405
Data point 30 : 43225.3794
Data point 31 : 43237.7533
Data point 32 : 43230.7843
Data point 33 : 43230.3275
Data point 34 : 43213.9055
Data point 35 : 43226.3736
Data point 36 : 43236.8287
Data point 37 : 43227.5152
Data point 38 : 43229.6852
Data point 39 : 43218.2508
Data point 40 : 43216.2645
Data point 41 : 43216.108
Data point 42 : 43222.8036
Data point 43 : 43227.3691
Data point 44 : 43246.262
Data point 45 : 43265.6731
Data point 46 : 43261.3533
Data point 47 : 43265.1947
Data point 48 : 43274.5045
Data point 49 : 43273.7366
Data point 50 : 43301.2328
Data point 51 : 43301.4552
Data point 52 : 43311.157
Data point 53 : 43318.5431
Data point 54 : 43313.2742
Data point 55 : 43305.7135
Data point 56 : 43309.3825
Data point 57 : 43324.4756
Data point 58 : 43330.7109
Data point 59 : 43333.8319
Data point 60 : 43353.1286
Data point 61 : 43372.0521
Data point 62 : 43400.0015
Data point 63 : 43421.5225
Data point 64 : 43388.3455
Data point 65 : 43382.8768
Data point 66 : 43389.8618
Data point 67 : 43410.1023
Data point 68 : 43386.9059
Data point 69 : 43399.4902
Data point 70 : 43387.1986
Data point 71 : 43419.003
Data point 72 : 43445.7588
Data point 73 : 43438.9243
Data point 74 : 43443.3843
Data point 75 : 43440.3487
Data point 76 : 43437.4055
Data point 77 : 43430.738
Data point 78 : 43451.762
Data point 79 : 43452.7259
Data point 80 : 43456.0684
Data point 81 : 43458.1253
Data point 82 : 43479.0447
Data point 83 : 43496.7625
Data point 84 : 43486.2976
Data point 85 : 43478.9283
Data point 86 : 43484.2095
Data point 87 : 43489.9117
Data point 88 : 43478.5918
Data point 89 : 43477.1431
Data point 90 : 43486.6044
Data point 91 : 43480.0352
Data point 92 : 43472.4512
Data point 93 : 43486.6375
Data point 94 : 43493.2865
Data point 95 : 43508.149
Data point 96 : 43515.1063
Data point 97 : 43538.4121
Data point 98 : 43551.4103
Data point 99 : 43574.2808
Data point 100 : 43603.6859
Data point 101 : 43610.6818
Data point 102 : 43589.2387
Data point 103 : 43623.1703
Data point 104 : 43650.6261
Data point 105 : 43658.2808
Data point 106 : 43654.6603
Data point 107 : 43654.164
Data point 108 : 43646.5888
Data point 109 : 43724.7223
Data point 110 : 43678.444
Data point 111 : 43652.9564
Data point 112 : 43638.1241
Data point 113 : 43681.9065
Data point 114 : 43653.0996
Data point 115 : 43636.8702
Data point 116 : 43635.4903
Data point 117 : 43646.514
Data point 118 : 43664.4099
Data point 119 : 43662.1573
Data point 120 : 43622.4766
Data point 121 : 43605.3416
Data point 122 : 43586.1805
Data point 123 : 43587.1526
Data point 124 : 43578.0167
Data point 125 : 43576.3765
Data point 126 : 43567.0559
Data point 127 : 43559.9888
Data point 128 : 43579.0011
Data point 129 : 43564.4359
Data point 130 : 43552.6954
Data point 131 : 43548.7785
Data point 132 : 43536.5845
Data point 133 : 43567.056
Data point 134 : 43580.5414
Data point 135 : 43590.3593
Data point 136 : 43590.1803
Data point 137 : 43630.7566
Data point 138 : 43679.77
Data point 139 : 43704.8212
Data point 140 : 43706.6986
Data point 141 : 43655.3703
Data point 142 : 43616.7582
Data point 143 : 43607.1109
Data point 144 : 43656.3017
Data point 145 : 43691.3749
Data point 146 : 43671.4183
Data point 147 : 43668.154
Data point 148 : 43649.8199
Data point 149 : 43667.4336
Data point 150 : 43669.8893
Data point 151 : 43672.5272
Data point 152 : 43691.1569
Data point 153 : 43687.7737
Data point 154 : 43696.6889
Data point 155 : 43712.8937
Data point 156 : 43721.0128
Data point 157 : 43742.563
Data point 158 : 43774.6681
Data point 159 : 43773.1034
Data point 160 : 43765.8754
Data point 161 : 43758.7725
Data point 162 : 43751.2554
Data point 163 : 43752.6414
Data point 164 : 43728.6054
Data point 165 : 43734.8235
Data point 166 : 43747.0082
Data point 167 : 43778.7363
Data point 168 : 43778.5657
Data point 169 : 43765.2517
Data point 170 : 43755.59
Data point 171 : 43729.0112
Data point 172 : 43723.811
Data point 173 : 43749.5691
Data point 174 : 43752.5579
Data point 175 : 43743.5206
Data point 176 : 43701.1156
Data point 177 : 43690.2989
Data point 178 : 43681.3701
Data point 179 : 43708.1708
Data point 180 : 43703.7888
Data point 181 : 43686.6722
Data point 182 : 43689.7071
Data point 183 : 43671.2456
Data point 184 : 43672.5137
Data point 185 : 43686.7611
Data point 186 : 43692.6895
Data point 187 : 43710.5718
Data point 188 : 43692.3911
Data point 189 : 43681.7241
Data point 190 : 43680.7547
Data point 191 : 43688.5651
Data point 192 : 43687.9258
Data point 193 : 43701.4133
Data point 194 : 43683.0457
Data point 195 : 43704.0917
Data point 196 : 43715.3974
Data point 197 : 43724.9496
Data point 198 : 43741.0956
Data point 199 : 43742.2303
Data point 200 : 43748.9365
Data point 201 : 43555.3463
Data point 202 : 43574.7118
Data point 203 : 43539.5445
Data point 204 : 43595.3094
Data point 205 : 43644.5782
Data point 206 : 43580.3771
Data point 207 : 43554.3129
Data point 208 : 43569.5608
Data point 209 : 43534.1271
Data point 210 : 43533.4113
Data point 211 : 43562.4946
Data point 212 : 43548.2053
Data point 213 : 43601.6458
Data point 214 : 43599.4184
Data point 215 : 43613.1014
Data point 216 : 43606.5114
Data point 217 : 43622.6384
Data point 218 : 43675.6031
Data point 219 : 43671.0878
Data point 220 : 43685.6747
Data point 221 : 43668.0342
Data point 222 : 43654.3955
Data point 223 : 43621.3756
Data point 224 : 43604.6002
Data point 225 : 43617.7603
Data point 226 : 43594.1977
Data point 227 : 43576.9656
Data point 228 : 43577.1579
Data point 229 : 43604.0001
Data point 230 : 43642.1558
Data point 231 : 43644.8545
Data point 232 : 43668.7947
Data point 233 : 43643.8269
Data point 234 : 43593.4194
Data point 235 : 43621.2421
Data point 236 : 43604.5905
Data point 237 : 43594.9433
Data point 238 : 43615.8015
Data point 239 : 43631.0714
Data point 240 : 43627.2821
Data point 241 : 43622.1054
Data point 242 : 43621.0521
Data point 243 : 43612.9835
Data point 244 : 43636.6516
Data point 245 : 43643.1042
Data point 246 : 43661.4485
Data point 247 : 43677.1615
Data point 248 : 43671.6634
Data point 249 : 43688.4937
Data point 250 : 43686.0204
Data point 251 : 43673.0782
Data point 252 : 43638.8407
Data point 253 : 43626.5926
Data point 254 : 43600.8496
Data point 255 : 43617.4053
Data point 256 : 43648.0707
Data point 257 : 43652.0763
Data point 258 : 43663.7632
Data point 259 : 43673.8172
Data point 260 : 43692.2085
Data point 261 : 43736.7519
Data point 262 : 43767.0352
Data point 263 : 43774.0312
Data point 264 : 43800.2603
Data point 265 : 43838.0412
Data point 266 : 43869.119
Data point 267 : 43864.1213
Data point 268 : 43862.637
Data point 269 : 43861.8388
Data point 270 : 43861.9127
Data point 271 : 43917.4848
Data point 272 : 43884.2455
Data point 273 : 43940.756
Data point 274 : 43990.2457
Data point 275 : 43982.5724
Data point 276 : 44012.5317
Data point 277 : 43991.1408
Data point 278 : 43922.777
Data point 279 : 43868.2471
Data point 280 : 43920.9504
Data point 281 : 43907.9835
Data point 282 : 43890.0793
Data point 283 : 43901.453
Data point 284 : 43937.0973
Data point 285 : 43964.9343
Data point 286 : 43985.5942
Data point 287 : 43989.2116
Data point 288 : 43943.6442
highest price is 44012.5317
lowest price is 43128.1818